runtime: nodejs18
instance_class: F1
env: standard

# Mount Cloud SQL instance(s) so your app can connect via unix socket.
# Replace <INSTANCE_CONNECTION_NAME> with your Cloud SQL instance connection name
cloud_sql_instances: "focus-vertex-481519-n4:us-central1:cloud-project"

env_variables:
  # The name of the secret (in Secret Manager) that contains DB credentials JSON
  SECRET_NAME: "db-credentials"
  # Optionally set the instance connection name here too (or set when deploying)
  INSTANCE_CONNECTION_NAME: "<PROJECT:REGION:INSTANCE>"

# Use gcp-build script to build Next.js during deployment
