runtime: nodejs24
instance_class: F1
env: standard

# Mount Cloud SQL instance(s) so your app can connect via unix socket.
# Replace <INSTANCE_CONNECTION_NAME> with your Cloud SQL instance connection name
beta_settings:
  cloud_sql_instances: "focus-vertex-481519-n4:us-central1:cloud-project"

env_variables:
  # DB credentials (bypassing Secret Manager for now)
  DB_USER: "myuser"
  DB_PASSWORD: "Ashu@123"
  DB_NAME: "mydb"
  # Cloud SQL instance connection name
  INSTANCE_CONNECTION_NAME: "focus-vertex-481519-n4:us-central1:cloud-project"

# Use gcp-build script to build Next.js during deployment
